# Generated by Django 3.0.5 on 2020-04-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=100)),
                ('Sets', models.IntegerField()),
                ('Reps', models.CharField(max_length=5)),
                ('RestTime', models.IntegerField()),
                ('ManagedReps', models.IntegerField()),
                ('ManagesSets', models.IntegerField()),
                ('CompletedDate', models.CharField(max_length=20)),
                ('IsCompleted', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
