# Generated by Django 3.0.5 on 2020-04-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20200425_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseList',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=100)),
                ('Exercises', models.ManyToManyField(to='myapi.Exercise')),
            ],
        ),
    ]
