# Generated by Django 3.0.5 on 2020-05-06 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_exerciselist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='ManagesSets',
            new_name='ManagedSets',
        ),
    ]
