# Generated by Django 3.0.5 on 2020-05-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_auto_20200506_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciselist',
            name='IsCompleted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
